import { shirt1, shirt2, shirt3, shirt4, shirt5, shirt6, shirt7,
    shirt8, shirt9, shirt10, shirt11, shirt12, shirt13, shirt14, shirt15, shirt16, 
    shirt17, shirt18, shirt19, shirt20, shirt21, shirt22, shirt23, shirt24, shirt25,
    shirt26, shirt27, shirt28, shirt29, shirt30, shirt31, shirt32, shirt33, shirt34,
    shirt35, shirt36, shirt37 } from '../assets';

export const data = [{id: 1, name: 'Florida Panthers Hockey Tee', description: 'XL', seller: 'Ahma Thrifts', price: '12', url: shirt1, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 2, name: 'University Of Oklahoma Tee', description: 'L', seller: 'Ahma Thrifts', price: '20', url: shirt2, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 3, name: 'Red Polo Rl Longsleeve', description: 'M', seller: 'Ahma Thrifts', price: '25', url: shirt3, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 4, name: 'Orange Polo Rl Cable Knit Sweater', description: 'M', seller: 'Ahma Thrifts', price: '38', url: shirt4, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 5, name: 'Yellow Polo Rl Knit Sweater', description: 'L', seller: 'Ahma Thrifts', price: '38', url: shirt5, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 6, name: 'Navy Polo Rl Cable Knit Sweater', description: 'L', seller: 'Ahma Thrifts', price: '38', url: shirt6, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 7, name: 'Pink Polo Rl Cable Knit Sweater', description: 'XL', seller: 'Ahma Thrifts', price: '34', url: shirt7, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 8, name: 'Miami Heat Basketball Tee ', description: 'XL', seller: 'Ahma Thrifts', price: '10', url: shirt8, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 9, name: 'Cherokee Embroidery Tee', description: 'XL', seller: 'Ahma Thrifts', price: '10', url: shirt9, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 10, name: 'Las Vegas Embroidery Tee ', description: 'L', seller: 'Ahma Thrifts', price: '10', url: shirt10, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 11, name: 'Bear Tee', description: 'XL', seller: 'Ahma Thrifts', price: '10', url: shirt11, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 12, name: 'Cat Tee', description: 'L', seller: 'Ahma Thrifts', price: '10', url: shirt12, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 13, name: 'Vintage Bear Tee', description: 'XL', seller: 'Ahma Thrifts', price: '10', url: shirt13, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 14, name: 'Kittens Tee', description: 'M', seller: 'Ahma Thrifts', price: '15', url: shirt14, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 15, name: 'Harley Tee', description: 'M', seller: 'Ahma Thrifts', price: '15', url: shirt15, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 16, name: 'Harley Tee', description: 'M', seller: 'Ahma Thrifts', price: '15', url: shirt16, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 17, name: 'Harley Tee', description: 'XXL', seller: 'Ahma Thrifts', price: '15', url: shirt17, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 18, name: 'Harley Tee', description: 'M', seller: 'Ahma Thrifts', price: '15', url: shirt18, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 19, name: 'Canada Harley Tee', description: 'XXL', seller: 'Ahma Thrifts', price: '15', url: shirt19, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 20, name: 'The Mountain Dog Tee', description: 'L', seller: 'Ahma Thrifts', price: '10', url: shirt20, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 21, name: 'Single Stitched Xmas Tee', description: 'S', seller: 'Ahma Thrifts', price: '10', url: shirt21, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 22, name: 'Vintage St Thomas Tee', description: 'XL', seller: 'Ahma Thrifts', price: '10', url: shirt22, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 23, name: 'Harley Tee', description: 'L', seller: 'Ahma Thrifts', price: '10', url: shirt23, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 24, name: 'Ksa Kickoff Football Tee', description: 'XL', seller: 'Ahma Thrifts', price: '10', url: shirt24, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 25, name: 'Canada Embroidery Tee', description: 'L', seller: 'Ahma Thrifts', price: '10', url: shirt25, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 26, name: 'Harley Tee', description: 'M', seller: 'Ahma Thrifts', price: '5', url: shirt26, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 27, name: 'Harley Tee', description: 'M', seller: 'Ahma Thrifts', price: '5', url: shirt27, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 28, name: 'Ou Russell Tee', description: 'L', seller: 'Ahma Thrifts', price: '5', url: shirt28, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 29, name: 'Nike Tee', description: 'XXL', seller: 'Ahma Thrifts', price: '5', url: shirt29, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 30, name: 'Sports Tee', description: 'XXL', seller: 'Ahma Thrifts', price: '5', url: shirt30, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 31, name: 'Nfl', description: 'L', seller: 'Ahma Thrifts', price: '5', url: shirt31, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 32, name: 'Dog Tee', description: 'S', seller: 'Ahma Thrifts', price: '5', url: shirt32, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 33, name: 'Champion Ape Tee', description: 'S', seller: 'Ahma Thrifts', price: '5', url: shirt33, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 34, name: 'Champion Lenoir Bears University ', description: 'S', seller: 'Ahma Thrifts', price: '5', url: shirt34, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 35, name: 'Puma Tee', description: 'M', seller: 'Ahma Thrifts', price: '5', url: shirt35, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 36, name: 'Nike Usa Tee', description: 'S', seller: 'Ahma Thrifts', price: '5', url: shirt36, telegramHandle: 'shermaineboey', category: 'shirt'}, 
{id: 37, name: 'Carolina Panthers Football Tee', description: 'S', seller: 'Ahma Thrifts', price: '5', url: shirt37, telegramHandle: 'shermaineboey', category: 'shirt'}]